format:
    html:
      html-math-method: katex
      embed-resources: false
execute:
    message: false
    warning: false
    error: false
    echo: false
    cache: false
editor: source
project:
  execute-dir: project
  output-dir: "Results"

