%% Cycle between dev and experts at center

graph LR;
  data[(Data)] ==> explore[Explore <br> Data] ==Summary==> expert[Expert <br> Review] ==> problem{Problem}
  problem ==Yes==> understand{Know<br>solution?}

  understand ==Yes==> newFeature[New <br> Feature] ==> explore

  understand --No--> advice{Data Manager <br>know?}

  advice --Yes--> newFeature
  advice --No--> ab(Best Guess + Note) --> newFeature 


  problem --No--> review{Code <br> review} -.No problem.->  Beta -.-> vProblem{Problem?} 
  review -.Problem .-> understand

  vProblem -.No.-> Version
  vProblem -.Yes.-> newFeature