flowchart LR
    subgraph Fetch
      subgraph NCCA
        nars[(NARS)] --> .readNCCAsites2010
        nars[(NARS)] --> .readNCCAsites2015
        nars[(NARS)] --> .readNCCAwq2010
        nars[(NARS)] --> .readNCCAwq2015
        nars[(NARS)] --> .readNCCActd2010
        nars[(NARS)] --> .readNCCActd2015
        nars[(NARS)] --> .readNCCAflags2010
        nars[(NARS)] --> .readNCCAflags2015
      end

      subgraph GLENDA 
        glenda[(GLENDA)] --> .readGLENDA
        glenda[(GLENDA)] --> .readGLENDAflags
        glenda[(GLENDA)] --> .readGLENDAsites
        seabird[(SeaBird Files)] --> .readSeabird
      end
      
      subgraph CSMI 
        CSMI[(CSMI)]
        CSMI --CSMI2010--> .readShapeCSMI2010
        CSMI --CSMI2015--> .readShapeCSMI2015
        CSMI --CSMI2020--> .readShapeCSMI2020
        CSMI --CSMIflags--> .readShapeCSMIflags
        CSMI --CSMImdl--> .readShapeCSMImdl
      end
      
      
      subgraph NOAA
        noaaWQ[(NOAA WQ)] --> .readShapeNOAAwq
        noaaCTD[(NOAA CTD)] --> .readShapeNOAActd
      end
    end
    %% connect fetch and normalize
    %% NCCA
    .readNCCAsites2010 --> .reshapeJoinNCCA
    .readNCCAsites2015 --> .reshapeJoinNCCA
    .readNCCAwq2010 --> .reshapeJoinNCCA
    .readNCCAwq2015 --> .reshapeJoinNCCA
    .readNCCActd2010 --> .reshapeJoinNCCA
    .readNCCActd2015 --> .reshapeJoinNCCA
    .readNCCAflags2010 --> .reshapeJoinNCCA
    .readNCCAflags2015 --> .reshapeJoinNCCA

    %% GLENDA
    .readGLENDA --> .joinGLENDA
    .readGLENDAflags --> .joinGLENDA
    .readGLENDAsites --> .joinGLENDA
    .readSeabird --> .joinGLENDA

    %% CSMI
    .readShapeCSMI2010 --> .joinCSMI
    .readShapeCSMI2015 --> .joinCSMI
    .readShapeCSMI2020 --> .joinCSMI
    .readShapeCSMIflags --> .joinCSMI
    .readShapeCSMImdl --> .joinCSMI

    %% NOAA
    .readShapeNOAActd --> .joinNOAA
    .readShapeNOAAwq --> .joinNOAA

    subgraph Normalize
      .reshapeJoinNCCA
      .joinGLENDA
      .joinCSMI
      .joinNOAA
    end

    .reshapeJoinNCCA --> .joinFullData
    .joinGLENDA --> .joinFullData
    .joinCSMI --> .joinFullData
    .joinNOAA--> .joinFullData

    subgraph Join
      .joinFullData
    end

    RenamingTable[(Expert \n Knowledge)] --> .renameAnalytes
    RenamingTable --> .convertUnits
    .joinFullData --> .renameAnalytes

    subgraph Standardize
      .renameAnalytes --> .convertUnits
    end