gantt
%% Finish hreview, Documentation, Beta testing data, and GUI
%% Data permissions
    title v1.0 Roadmap
    dateFormat YYYY-MM
    axisFormat %b-%y
    section GLENDA
        WQ      :glendawq, 2023-10, 120d
        CTD (Seabird)    :glendactd, 2024-04, 30d
        Revisions : glendarevise, 2024-05, 1w
    section NCCA 
        2010 :ncca2010, 2023-12, 90d
        2015 :ncca2015, 2023-12, 90d
        2021 :ncca2021, after shinySketch, 4w
        Revisions : nccarevise, after glendarevise, 1w
    section CSMI 
        2015 :csmi2015, 2024-02, 60d
        2021 :csmi2021, 2024-07, 30d
        Revisions : csmirevise, after nccarevise, 1w
    section NOAA 
        WQ : NOAAWQ, 2024-06, 30d
    section Standardize <br> names/units
        Standarize Names :2023-12, 2024-05
        Standarize Units :2024-03, 2024-06
    section Documentation 
        User : userDoc, 2024-05, 90d 
        Developer : devDoc, 2024-01, 2024-08 
    section Shiny app
        Sketch : shinySketch, 2024-06, 1w
        Function : shiny, after cr2 , 2w
    section Review
        Code Review 1 :cr1, 2024-04, 2024-07
        Code Review 2 :cr2, after ncca2021 , 15d
        Beta Data: betaData, after cr2, 2w
        Beta Package: betaPackage, after betaData, 2w
        V1 : milestone, v1, 2024-10, 1d