---
title: "Chla sample summary"
date: today
---

```{r setup}
library(tidyverse)
library(fuzzyjoin)
library(gganimate)
theme_set(theme_minimal())

df <- readRDS("fullData.Rds")

chlaDF <- df %>% 
  filter(CodeName == "Chla") %>%
  mutate(
    # march 20th as beginning of spring
    season = case_when(
      month(sampleDateTime) %in% 3:5 ~ "Spring",
      month(sampleDateTime) %in% 6:8 ~ "Summer",
      month(sampleDateTime) %in% 9:11 ~ "Fall",
      month(sampleDateTime) %in% c(1, 2,12) ~ "Winter"
    ),
    season = factor(season, levels = c("Spring", "Summer", "Fall", "Winter")),
    Year = year(sampleDateTime)
  )
``` 
  
  
# Through Time
```{r timePlot}
chlaDF %>% 
  ggplot(aes(x = sampleDateTime, fill = Study)) +
  geom_histogram() +
  ggtitle("Number of CHLA observations over time")
ggsave("LMchlaObsOverTime.png", dpi = 300)

chlaDF %>%
  pivot_longer(contains("Depth"), values_to = "Depth")  %>%
  ggplot(aes(x = sampleDateTime, y = Depth, col = season)) +
  geom_point() + 
  scale_y_reverse() +
  facet_wrap(~name, ncol = 1)
ggsave("LMchlaSampleDepths.png", dpi = 300)
chlaDF %>%
  pivot_longer(contains("Depth"), values_to = "Depth")  %>%
  mutate(timeGroup = paste(Year, season, sep = "-")) %>%
  ggplot(aes(y = Depth)) +
  geom_histogram() + 
  scale_y_reverse() +
  facet_wrap(~name, ncol = 1) +
  transition_states(timeGroup, state_length=10, transition_length=0) + 
  labs(title = 'Year: {closest_state}')
gganimate::anim_save("LMchlaDepths.gif")
```
  

# Through space
```{r spacePlot}
lakes <- sf::read_sf("ne_50m_lakes.shp")
ggplot(lakes) +
  geom_sf(fill = "lightblue") +
  coord_sf(xlim = c(-88, -85), ylim = c(41.5, 46.2)) +
  theme(panel.background = element_rect(fill = '#d0d890'),
        panel.grid = element_line(color = '#00000010')) +
  geom_jitter(data= chlaDF, aes(x = Longitude, y = Latitude), size = 3, col = "red",  alpha = 0.2) +
  ggtitle("Chla Observations")
ggsave("LMchlaObsInSpace.png", dpi = 300)
```

# Through space and time
```{r spaceTime}

ggplot(lakes) +
  geom_sf(fill = "lightblue") +
  coord_sf(xlim = c(-88, -85), ylim = c(41.5, 46.2)) +
  theme(panel.background = element_rect(fill = '#d0d890'),
        panel.grid = element_line(color = '#00000010')) +
  geom_jitter(data= chlaDF, aes(x = Longitude, y = Latitude), size = 3, col = "red",  alpha = 0.2) +
  transition_states(Year, state_length=2, transition_length=0) + 
  labs(title = 'Year: {closest_state}')
gganimate::anim_save("LMsampleCoordsThroughTime.gif")
```

