---
title: "Chlorophyll sampling summary"
author: "Christian Coffman"
date: 8-16-2024
format: pdf
---

```{r setup}
#| echo: false
library(tidyverse)
library(kableExtra)
df <- readRDS("fullData.Rds")

chloroObs <- df %>% filter(CodeName == "Chla") %>% drop_na(RESULT)
```

```{r}
#| label: tbl-cars
#| tbl-colwidths: [60,40]
#| echo: false

chloroObs %>%
  reframe(count = n(), .by=c(Study)) %>%
  kable() %>%
  kableExtra::kable_paper()
```


```{r}
unzip("ne_50m_lakes.zip")
theme_set(theme_bw())
lakes <- sf::read_sf("ne_50m_lakes.shp")

windows();ggplot(lakes) +
  geom_sf(fill = "lightblue") +
  coord_sf(xlim = c(-88, -85), ylim = c(41.5, 46.2)) +
  theme(panel.background = element_rect(fill = '#d0d890'),
        panel.grid = element_line(color = '#00000010')) +
  geom_point(data= rounded, aes(x = Long2, y = Lat2, size = 1e-2), col = "red",  alpha = 0.2)+
  geom_point(data= rounded, aes(x = Long3, y = Lat3, size = 1e-3), col = "yellow",  alpha = 0.2)+
  geom_point(data= rounded, aes(x = Long4, y = Lat4, size = 1e-4), col = "black",  alpha = 0.2) 
  scale_radius(range = range(c(1e-2, 1e-4)/2))


```